import Image from 'next/image'
// import './globals.css'

export const metadata ={
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph: {
    title: "Create Next App",
    description: "Generated by create next app",
  }
}

export default function Home() {
  const h1 = "mt-10 mb-6 text-2xl font-bold"
  const h2 = "mt-8 mb-4 text-xl font-bold"
  const p = "mt-4 mb-2"

  return (
    <>
      <main>
        <h1 className={h1}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={p}>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Sint error consectetur modi odio obcaecati tempore dignissimos assumenda, eum reiciendis dolores magni autem at debitis voluptas. Rem ipsa deleniti autem dignissimos.
        </p>
      </main>
    </>
  )
}
