import Image from 'next/image'
// import './globals.css'

export const metadata ={
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph: {
    title: "Create Next App",
    description: "Generated by create next app",
  }
}

export default function Home() {
  const h1 = "mt-10 mb-6 text-2xl font-bold"
  const h2 = "mt-8 mb-4 text-xl font-bold"
  const p = "mt-4 mb-2"

  return (
    <>
      <main>
        <h1 className={h1}>
         Nossos Produtos
        </h1>
      </main>
    </>
  )
}
